#!/usr/bin/python3
# -*- coding:utf-8 -*-


import argparse
import json
from src.Cart import Cart
from src.Item import Item

# constants path
PRODUCTS_PATH = 'src/data/products.json'

products = json.load(open(PRODUCTS_PATH, 'r'))

# parser for command line arguments
parser = argparse.ArgumentParser(description='Price a cart of products and apply discounts')
parser.add_argument('--product', help='product argument，required, format: --product:T-shirt', action='append',
                    required=True)
args = parser.parse_args()


def main():
	"""
	Entry point of the program
	parse the command line arguments and print the invoice
	:return: None
	"""
	try:
		inputs = args.product
		res = []
		for item in inputs:
			if item in products:
				res.append(
					Item(item, products[item]['item price'], products[item]['shipped from'], products[item]['weight']))
		if len(res) == 0:
			print('No product found')
		else:
			cart = Cart(res)
			print(cart.get_cart_invoice())
	except Exception as e:
		print(e)


if __name__ == '__main__':
	main()
